#-------------------------------
# General Site Settings
baseURL = "https://janabergant.com/"
languageCode = "sl-si"
title = "Hipnoterapija"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Izboljšaj svoje spanje, shujšaj ter pridobi na samozavesti s pomočjo certificirane hipnoterapevtke Jane"


[params.global.image]
  enable = true
  cover__image = 'https://via.placeholder.com/1920x600' # Add global cover image (This field adds a background to the top and bottom of the site.)

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Domov"
    url = "/"
    weight = -1

    [[menu.main]]
    parent = "Storitve"
    name = "Hipnoza za spanje"
    url = "/storitve/hipnoza-za-spanje/"
    weight = 2

    [[menu.main]]
    parent = "Storitve"
    name = "Hipnoza za hujšanje"
    url = "/storitve/hipnoza-za-hujsanje/"
    weight = 2

    [[menu.main]]
    parent = "Storitve"
    name = "Hipnoza za samozavest"
    url = "/storitve/hipnoza-za-samozavest/"
    weight = 2



  [[menu.main]]
    identifier = "blog"
    name = "Članki"
    url = "/clanki/"
    weight = 4

  [[menu.main]]
    name = "O hipnoterapiji"
    url = "/hipnoterapija/"
    weight = 5

  [[menu.main]]
    name = "O Jani"
    url = "/jana-bergant/"
    weight = 6


  # Call to action button
  [params.menu.button]
    cta__button__text = "Spoznavni klic"


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Jana Bergant"
    author__title = "Živjo, sem Jana"
    author__bio = "S hipnoterapijo ti pomagam bolje spati, shujšati in postati bolj samozavestna in opolnomočena. Na spletni strani najdeši vse, kar potrebuješ za pozitivne spremembe v svojem življenju."
    author__bio_extended = "Dovolj nespečnosti, obsedenosti s kilami ter slabe samozavesti."
    author__image = "https://via.placeholder.com/600x600"
    author__avatar = "https://via.placeholder.com/200x200"
    button__text = "Storitve"


  #-------------------------------
  # Projects Settings
  [params.storitve]
    enable = true
    projects__title= "Kako ti <span class='text-span'>pomagam</span>"  
    projects__description= "Pri delu vključujem hipnoterapijo in tehnike za izboljšanjev vzorcev spanja, pomoč pri hujšanju, tehnike za krepitve zaupanja in več."
    projects__sub_description= "Nauči se kako hipnoterapija deluje in kako je lahko koristna za vse, ki želijo narediti pozitivne spremembe v svojem življenju."

  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Zadovoljne <span class='text-span'>stranke</span>" # Add a 'text-span' class to highlight text.
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Zaire Baptista"
    image = "https://via.placeholder.com/250x250"
    designation = "Traveler"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Ann Philips"
    image = "https://via.placeholder.com/250x250"
    designation = "Designer"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Roger Bergson"
    image = "https://via.placeholder.com/250x250"
    designation = "CEO, Founder"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Julie Arnold"
    image = "https://via.placeholder.com/250x250"
    designation = "Full stack developer"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Zadnji <span class='text-span'>članki</span>" # Add a 'text-span' class to highlight text.
    blog__description = ""


  #-------------------------------
  # Contact Settings
  [params.contact]
    enable = false 
    contact__email = "your@email.com" # Add your form_id
    contact__title = "<span class='text-span'>Get</span> in touch" # Add a title to your form
    contact__description = "Avenco comes with a built-in contact form." # Add a description to your form

    # NOTE
    # Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__title = "<span class='text-span'>Join</span> my mailing list" # Add your title
    mailchimp__text = "Get the best inspiration and, cool stuff about design!" # Add descriptions to the form. If you want to use more than one sentence, be sure to separate them with a comma.
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


  #-------------------------------
  # Footer Settings
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # Other icons can be found at https://ionicons.com/v4/


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false